[package]
name = "rv32g-emulator"
version = "0.1.0"
authors = ["mix64"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elf = "0.0.10"